config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles, :stocks
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "karen", password: "password",
except: [:index, :show]

  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:date, :savings_accounts, :checking_accounts, :high_yield_savings, :regular_savings, :debt)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def new
    @stock = Stock.new
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to @stock
    else
      render 'new'
    end
  end

  def update
    @stock = Stock.find(params[:id])

    if @stock.update(stock_params)
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    redirect_to stocks_path
  end

  private
  def stock_params
    params.require(:stock).permit(:date, :vtiax, :vtsax, :total_invested, :change)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <p>
    <%= form.label :date %> <br>
    <%= form.date_select :date, :start_year=>1950 %>
  </p>

  <p>
    <%= form.label :checking_accounts %><br>
    <%= form.text_field :checking_accounts, required:true, :default=>0%>
  </p>

  <p>
    <%= form.label :regular_savings %><br>
    <%= form.text_field :regular_savings, required:true, :default=>0%>
  </p>

  <p>
    <%= form.label :high_yield_savings %><br>
    <%= form.text_field :high_yield_savings, required:true, :default=>0%>
  </p>

  <p>
    <%= form.label :debt %><br>
    <%= form.text_field :debt, required:true, :default=>0%>
  </p>

  <p>
    <%= form.submit%>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Finance Updates</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Checking Accounts</th>
    <th>Savings Accounts</th>
    <th>Debt</th>
    <th>Total</th>

  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.date %></td>
      <td><%= article.checking_accounts%></td>
      <td><%= article.savings_accounts %></td>
      <td><%= article.debt %></td>
      <td><%= article.total%></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article),
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Back', welcome_index_path %>

app/views/articles/new.html.erb
<h1>Savings Update</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong> Date:</strong>
  <%= @article.date %>
</p>

<p>
  <strong>Checking Accounts:</strong>
  <%= @article.checking_accounts%>
</p>

<p>
  <strong>Savings Accounts:</strong>
  <%= @article.savings_accounts = @article.high_yield_savings + @article.regular_savings %>
  <% @article.save %>

</p>

<p>
  <strong>Debt:</strong>
  <%= @article.debt %>
</p>

<p>
  <strong>Total:</strong>
  <%= @article.total = @article.savings_accounts + @article.checking_accounts - @article.debt %>
  <% @article.save %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with model: @stock, local: true do |form| %>

<p>
  <%= form.label :date %> <br>
  <%= form.date_select :date, :start_year=>1950 %>
</p>

<p>
  <%= form.label :vtiax %><br>
  <%= form.text_field :vtiax, required: true, :default=>0 %>
</p>

<p>
  <%= form.label :vtsax %><br>
  <%= form.text_field :vtsax, required: true, :default=>0 %>
</p>

<p>
  <%= form.label :total_invested %><br>
  <%= form.text_field :total_invested, required: true, :default=>0 %>
</p>

<p>
  <%= form.submit%>
</p>



<% end %>

app/views/stocks/edit.html.erb
<h1>Edit Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Stock Log</h1>

<table>
  <tr>
    <th>Date</th>
    <th>VTIAX</th>
    <th>VTSAX</th>
    <th>Total Invested</th>
    <th>Change</th>
  </tr>

  <% @stocks.each do |stock| %>
    <tr>
      <td><%= stock.date %></td>
      <td><%= stock.vtiax %></td>
      <td><%= stock.vtsax %></td>
      <td><%= stock.total_invested %></td>
      <td><%= stock.change %> </td>
      <td><%= link_to 'Show', stock_path(stock) %></td>
      <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
      <td><%= link_to 'Delete', stock_path(stock),
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Back', welcome_index_path %>

app/views/stocks/new.html.erb
<h1>Stock Update</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p>
  <strong> Date:</strong>
  <%= @stock.date %>
</p>

<p>
  <strong>VTIAX:</strong>
  <%= @stock.vtiax %>
</p>

<p>
  <strong>VTSAX:</strong>
  <%= @stock.vtsax %>
</p>

<p>
  <strong>Total Invested:</strong>
  <%= @stock.total_invested %>
</p>

<p>
  <strong>Change:</strong>
  <%= @stock.change = (@stock.total_invested - (@stock.vtiax + @stock.vtsax))*(-1)  %>
  <% @stock.save %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/welcome/index.html.erb
<h1>Finance Dashboard</h1>
<%= link_to 'Savings Log', controller: 'articles' %>
<%= link_to 'Savings Update', new_article_path %>
<br><br>
<%= link_to 'Stock Log', controller: 'stocks' %>
<%= link_to 'Stock Update', new_stock_path %>
<br>
<br>

<h1> Savings </h1> <br>

<%= line_chart [
  { name: 'checking_accounts', data: Article.group(:date).maximum(:checking_accounts) },
  { name: 'savings_accounts', data: Article.group(:date).maximum(:savings_accounts) },
  { name: 'debt', data: Article.group(:date).maximum(:debt) },
] %>

<br>
<h1> Investments </h1> <br>

<%= line_chart [
  { name: 'vtiax', data: Stock.group(:date).maximum(:vtiax)},
  { name: 'vtsax', data: Stock.group(:date).maximum(:vtsax)},
  { name: 'total_invested', data: Stock.group(:date).maximum(:total_invested)},
  { name: 'change', data: Stock.group(:date).maximum(:change)},

] %>